version: "3.1"
networks:
  intra:
  extra:
  
services:
  node:
    container_name: nodeapp
    volumes:
      - .:/usr/src/app
    build: .
    depends_on:
      - mongo
    ports:
      - "8080"
    deploy:
      restart_policy:
        condition: always
        delay: 10s
    networks:
      intra:
        aliases:
          - nodeapp
  mongo:
    image: 'mongo'
    container_name: mongoapp
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017"
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    networks:
      intra:
        aliases:
          - mongodb
  nginx:
    image: nginx:1.13
    container_name: nginxapp
    ports:
      - "80:80"
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    volumes:
      - ./nginx:/etc/nginx
    networks:
      - intra
      - extra